[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.npm"]

[phases.install]
cmds = [
  "cd frontend && npm ci",
  "cd backend && npm ci"
]

[phases.build]
cmds = [
  "cd frontend && npm run build",
  "cd backend && npx prisma generate && npm run build"
]

[start]
cmd = "node backend/dist/app.js"
